### ISSUE TITLE
Run npm publish

### ISSUE THREAD

**Issue by gwlortscher** [benefitcloud/ember-cli-uploader#4]
Thanks for writing this package! It looks like you've already tagged 0.3.9, but npm only pulls down 0.3.8 (https://www.npmjs.com/package/ember-cli-uploader). Directly updating bower.json worked in the meantime.

**Comment by digitaltoad** [comment]
Sorry about that. I'll get it fixed.

—
Josh

**Comment by digitaltoad** [comment]
All set.
