### ISSUE TITLE
ENOENT, no such file or directory '/Users/jc/test-app/tmp/concat_with_maps-input_base_path-GwA43Z4M.tmp/0/bower_components/ember-uploader/dist/ember-uploader.named-amd.js'

### ISSUE THREAD

**Issue by jcope2013** [benefitcloud/ember-cli-uploader#9]
for some reason the bower package doesn't have this file anymore under dist so this line errors out

https://github.com/benefitcloud/ember-cli-uploader/blob/master/index.js#L10

the only file under dist is ember-uploader.js

I am using 0.3.11 of ember-uploader in my bower.json, this seems like a relatively new problem (sometime in last few days as it was working fine until then), I am thinking it's an issue on bower's end (tried a few bower versions to make sure nothing funky was up, no luck) or somehow the 0.3.11 version got republished with missing files which I believe to be the case as I don't see how it was working in the past otherwise

as a temp fix I can do `"ember-uploader": "benefitcloud/ember-uploader#master"` in my bower.json and it fixes it

**Comment by jozefvaclavik** [comment]
Having same issue. How did you solve it?

**Comment by jcope2013** [comment]
I believe it was just a corrupt bower install on my machine, the issue was fixed once I upgraded my bower
